name: Build & Test
on: push

jobs:
  scalafmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT & ivy cache
        uses: actions/cache@v1
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/plugins.sbt') }}-${{ hashFiles('**/build.properties') }}
      - name: Scalafmt
        run: sbt scalafmtCheckAll

  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT & ivy cache
        uses: actions/cache@v1
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/plugins.sbt') }}-${{ hashFiles('**/build.properties') }}
      - name: Compile
        run: sbt compile

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT & ivy cache
        uses: actions/cache@v1
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/plugins.sbt') }}-${{ hashFiles('**/build.properties') }}
      - name: Run tests
        run: sbt test

  examples:
    name: Compile Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT & ivy cache
        uses: actions/cache@v1
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/plugins.sbt') }}-${{ hashFiles('**/build.properties') }}
      - name: Compile examples
        run: sbt it:compile

  scapegoat:
    name: Scapegoat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT & ivy cache
        uses: actions/cache@v1
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/plugins.sbt') }}-${{ hashFiles('**/build.properties') }}
      - name: Run scapegoat
        run: sbt scapegoat